// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqv_vYAQkd6-pLXrNIdJUKvA-YbVrwzEw',
    appId: '1:302206761540:android:d5f91fd78f1b0c7f9ada11',
    messagingSenderId: '302206761540',
    projectId: 'dexueyuan-68769',
    storageBucket: 'dexueyuan-68769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24EzjurQM7073lNWOcgoHopLhx6p2ids',
    appId: '1:302206761540:ios:8d7a67a4a81f88999ada11',
    messagingSenderId: '302206761540',
    projectId: 'dexueyuan-68769',
    storageBucket: 'dexueyuan-68769.firebasestorage.app',
    androidClientId: '302206761540-j0udll8imi95gqifp70nr5l6sitkmc6c.apps.googleusercontent.com',
    iosClientId: '302206761540-tiva7v6fqad94jms3ffirpm8p5b4n7cq.apps.googleusercontent.com',
    iosBundleId: 'com.dxy.holdem',
  );

}